#!/usr/bin/env python3
"""Patch players-data.js with team schedules and per-player news blurbs.

Usage: python3 patch-extras.py <player-extras-workflow-output.json>
Run after merge-data.py; safe to re-run (overwrites schedules/blurbs each time).
"""

import json
import re
import sys
from datetime import date


def norm_name(name):
    s = str(name).lower()
    s = re.sub(r"[.'’,-]", "", s)
    s = re.sub(r"\b(jr|sr|ii|iii|iv|v)\b", "", s)
    return re.sub(r"\s+", " ", s).strip()


def main():
    with open(sys.argv[1]) as f:
        extras = json.load(f)["result"]

    raw = open("players-data.js").read()
    data = json.loads(raw.split("=", 1)[1].rstrip().rstrip(";"))

    # --- Schedules: {ABBR: ["KC", "@DAL", ..., "BYE"]} indexed by week-1 ---
    schedules = {}
    problems = []
    for conf in ("schedAFC", "schedNFC"):
        for team in (extras.get(conf) or {}).get("teams") or []:
            abbr = str(team["abbr"]).upper()
            weeks = [None] * 18
            for g in team.get("games", []):
                w = int(g["week"])
                if 1 <= w <= 18:
                    weeks[w - 1] = str(g["opp"]).upper()
            missing = [i + 1 for i, x in enumerate(weeks) if x is None]
            if missing:
                problems.append(f"{abbr}: missing weeks {missing}")
            # cross-check bye against the verified bye table
            bye_claim = data["byes"].get(abbr)
            if bye_claim and weeks[bye_claim - 1] not in (None, "BYE"):
                problems.append(
                    f"{abbr}: schedule week {bye_claim} is {weeks[bye_claim - 1]}, but verified bye is week {bye_claim}"
                )
            schedules[abbr] = [x or "?" for x in weeks]
    data["schedules"] = schedules

    # --- Blurbs ---
    blurb_by_name = {}
    for band in extras.get("blurbs") or []:
        for p in band.get("players") or []:
            b = (p.get("blurb") or "").strip()
            if b:
                blurb_by_name[norm_name(p["name"])] = b
    matched = 0
    for p in data["players"]:
        b = blurb_by_name.get(norm_name(p["name"]))
        if b:
            p["blurb"] = b
            matched += 1

    data["extrasGenerated"] = date.today().isoformat()

    with open("players-data.js", "w") as f:
        f.write("// Generated by merge-data.py + patch-extras.py — do not hand-edit.\n")
        f.write("window.DRAFT_DATA = ")
        json.dump(data, f, indent=1)
        f.write(";\n")

    print(f"schedules: {len(schedules)}/32 teams")
    print(f"blurbs gathered: {len(blurb_by_name)}; matched to pool: {matched}")
    if problems:
        print("PROBLEMS:")
        for p in problems:
            print("  " + p)
    else:
        print("no schedule gaps; all byes consistent with verified table")


if __name__ == "__main__":
    main()
